pnp/script-samples

scripts/spo-add-document-library-webpart-to-page/README.md
scripts/spo-add-document-library-webpart-to-page/assets/sample.json

The aim of this PR is to add CLI for Microsoft 365 equivalent -
https://pnp.github.io/script-samples/spo-add-document-library-webpart-to-page/README.html?tabs=pnpps
#117
The result of running the script compared in m365 CLI
page created
one of the pages looks like

Add CLI for Microsoft 365 to Add a document library web part to a page (and only show a specific folder)

---

scripts/report-private-teams-excel/README.md
scripts/report-private-teams-excel/assets/sample.json

The aim of this PR is to add CLI for Microsoft 365 equivalent -
https://pnp.github.io/script-samples/report-private-teams-excel/README.html?tabs=pnpps
#120
running the script
excel result
file added to SP

Add CLI for Microsoft 365 to Report of Private Teams channels to Excel

---

scripts/remove-delete-option-library/README.md
scripts/remove-delete-option-library/assets/sample.json

The aim of this PR is to add CLI for Microsoft 365 equivalent -
https://pnp.github.io/script-samples/remove-delete-option-library/README.html?tabs=pnpps
#121
result of the script

Add CLI for Microsoft 365 to Remove delete option on a document library

---

scripts/generate-markdown-lcids/README.md
scripts/generate-markdown-lcids/assets/sample.json

The aim of this PR is to add CLI for Microsoft 365 equivalent -
https://pnp.github.io/script-samples/generate-markdown-lcids/README.html?tabs=pnpps
#118
result of the script

Add CLI for Microsoft 365 to Generate Markdown Report of LCIDs

---

docfx/templates/material/styles/main.css

Fixed visual bug on small cards where the description and title is overflowing over the author metadata
Reference #219 Issue

Fixes for small screen display overlaps

---

scripts/flow-runs-day-summary/README.md
scripts/flow-runs-day-summary/assets/sample.json

With the creation of the Get-PnPFlowRuns PnP PowerShell cmdlet recently I have now updated the flow run day summary - post to adaptive card example to add PnP PS.
Have also updated the intro wording to tell the user how to create an incoming webhook for the Microsoft Team.

Updated flow run day summary example to add PnP PS

---

scripts/spo-create-bulk-libraries/README.md
scripts/spo-create-bulk-libraries/assets/sample.json

Closes #274 
* `m365 spo list view add` command is in preview at this moment. You should use v5.3.0 preview version of M365 CLI
* Replaced the `TargetSitePartUrl` and the `PartTenant` parameters by `TargetWebUrl`. Right now we assume that the target SharePoint URL is `"https://$($PartTenant).sharepoint.com/sites/$($TargetSitePartUrl)"`. This is not always the case, tenants are able to use other prefixes than `/sites`.

M365 CLI - Bulk library generation

---

scripts/reset-files-permission-unique-to-inherited/README.md
scripts/reset-files-permission-unique-to-inherited/assets/sample.json

Added CLI for M365 version for script [Reset files permissions unique to Inherited](https://pnp.github.io/script-samples/reset-files-permission-unique-to-inherited/README.html?tabs=pnpps)
Closes #281
@Adam-it 
I did it bit differently by using [m365 spo file list](https://pnp.github.io/cli-microsoft365/cmd/spo/file/file-list/), so that we can recursively get all the files at one go.
Please have your review.

Added CLI for M365 version for script "Reset files permissions unique to Inherited"

---

scripts/planner-copy-planner-plan/README.md

Noticed that the script `Copy Planner plan` has a markdown code block tag displayed.

Markdown code block fix

---

scripts/planner-copy-planner-plan/README.md
scripts/planner-copy-planner-plan/assets/sample.json

Because there is a new CLI version, following adjustments were made:
* Copy priority of task as well
* Removed deprecated command `m365 planner task details get`
* Removed conversion method to convert date to valid ISO string (this has been fixed)

`Copy Planner Plan` updated to work with CLI v5.4.0

---

scripts/aad-delete-m365-groups/README.md
scripts/aad-flag-groups-with-user-names/README.md
scripts/flow-inventory-flows-by-author/README.md
scripts/spo-grant-api-permissions-aad/README.md
scripts/spo-hide-list-from-site-contents/README.md
scripts/spo-list-all-application-customizers/README.md
scripts/spo-list-site-app-catalogs/README.md
scripts/spo-list-tenant-wide-extensions/README.md
scripts/spo-remove-custom-themes/README.md
scripts/spo-remove-orphaned-redirect-sites/README.md
scripts/spo-remove-site-designs/README.md
scripts/spo-remove-site-scripts/README.md
scripts/teams-deploy-teams-app/README.md
scripts/teams-govern-orphan-teams/README.md
scripts/teams-list-teams-app-usage/README.md
scripts/teams-remove-wikitab-teams/README.md
scripts/todo-cleanup-completed-todos/README.md

- fixing a naming issue
closes #381

fix naming

---

scripts/graph-download-office-documents-as-pdf/README.md
scripts/graph-download-office-documents-as-pdf/assets/sample.json

The aim of this issue would be to add a [CLI for M365](https://pnp.github.io/cli-microsoft365/) version of script [Download contents of Document library as PDF](https://pnp.github.io/script-samples/graph-download-office-documents-as-pdf/README.html?tabs=pnpps).
Closes: #357
After running the script locally I have the same files as in the related document library converted to pdfs

CLI for M365 version of script - Download contents of Document library as PDF

---

scripts/ReportTermUse/README.md
scripts/ReportTermUse/assets/sample.json

The aim of this issue would be to add a [CLI for M365](https://pnp.github.io/cli-microsoft365/) version of script [Reports to Excel where the specified Term is used](https://pnp.github.io/script-samples/ReportTermUse/README.html?tabs=pnpps).
Closes: #308
After running the script locally I have the csv report from all sites, lists, etc that use this termset field

CLI for M365 version of script -Reports to Excel where the specified Term is used

---

scripts/teams-list-teams-owners-and-members/README.md
scripts/teams-list-teams-owners-and-members/assets/sample.json

- Update PnP PowerShell script to list all Microsoft Teams team's owners and members
- Added CLI for Microsoft 365 script to list all Microsoft Teams team's owners and members

Sample Update - List all Microsoft Teams team's Owners and Members

---

scripts/spo-create-library-add-contenttype/README.md
scripts/spo-create-library-add-contenttype/assets/sample.json

- Added CLI for Microsoft 365 script sample that creates a SharePoint document library by checking whether it exists or not. Adds custom content type to the document library and makes it as a default content type.

Sample Update - Create Library and add custom Content Type

---

scripts/spo-update-highlightcontentwebpart-seeall/README.md
scripts/spo-update-highlightcontentwebpart-seeall/assets/sample.json

- Quick fixes to the script sample: [Hide the 'See All' Button in the Highlighted Content Web Part](https://pnp.github.io/script-samples/spo-update-highlightcontentwebpart-seeall/README.html?tabs=pnpps)

Sample Update - Quick fixes to the script sample

---

scripts/spo-enable-disable-search-crawling/README.md
scripts/spo-enable-disable-search-crawling/assets/sample.json

- Added CLI for Microsoft 365 script sample that will allow you to enable or disable the Search crawling on a SharePoint site or a library.

Sample Update - Enable/Disable Search Crawling on Sites and Libraries

---

scripts/spo-export-content-type-details-to-csv/README.md
scripts/spo-export-content-type-details-to-csv/assets/sample.json

- Added CLI for Microsoft 365 script samples that exports all content types available on a SharePoint site, including basic information such as Name, ID, Scope, Schema, Fields, and more, into a CSV format.

Sample Update - Export Content Type Details To CSV

---

scripts/aad-replace-owner-with-a-different-one/README.md
scripts/aad-replace-owner-with-a-different-one/assets/sample.json

- Added CLI for Microsoft 365 script samples that finds all the Microsoft 365 Groups that a user is an Owner of and replace them with someone else, it is useful when an employee leaves and ownership needs to be updated.

Sample Update - Replace an owner in a Microsoft 365 Group or Microsoft Team

---

scripts/aad-delete-m365-groups-and-sharepoint-sites/README.md
scripts/aad-delete-m365-groups-and-sharepoint-sites/assets/sample.json

- Added CLI for Microsoft 365 script samples that shows how you can delete Microsoft 365 Groups and associated SharePoint Online sites in your development environment.

Sample Update - Delete all Microsoft 365 groups and SharePoint sites

---

docfx/templates/material/styles/docfx.js
docfx/templates/material/styles/main.css
docfx/templates/material/styles/site.css

References #726 
Small adjustments to the nav header and when the pencil icons shows

Navigation and contribution links tweak

---

scripts/spo-document-sets-modern-new-form/README.md
scripts/spo-document-sets-modern-new-form/assets/sample.json

Adapted @Tanddant's script to work on the Content Type Hub for centralized modernization.

Enable modern creation forms for Document sets - Added CTH variation of the script
