- docfx/templates/material/styles/extra.css
- docfx/templates/material/styles/loadsamples.js
- docfx/templates/material/styles/site.css
- Tested on ipad portrait, landscape, ios portraits, small, medium and large monitors.
> Visual updates to improve readability

- scripts/spo-list-items-large-lists/README.md
- scripts/spo-list-items-large-lists/assets/sample.json
Issue #40 
additional sample using CLI added.
> CLI example added

- scripts/aad-manage-group-users/README.md
Fixed article format
Retested using local framework
> Fix for broken article rendering

- scripts/spo-add-site-design-with-custom-list/README.md
- scripts/spo-add-site-design-with-custom-list/assets/sample.json
Added CLI sample for the same. Issue #112
> added cli sample

- docfx/assets/help/cli.help.json
- docfx/assets/help/powershell.help.json
- docfx/assets/help/spoms.help.json
Updated cmdlet help system source help files
> Updated help based on new cmdlets

- scripts/flow-export-all-flows-in-environment/README.md
- scripts/flow-export-all-flows-in-environment/assets/sample.json
🎯 PR aim
Added script for PnP PowerShell for existing sample
✔ What was done
> Added PnP PowerShell example to existing export all flows CLI sample

- scripts/spo-list-site-externalusers/README.md
- scripts/spo-list-site-externalusers/assets/sample.json
New sample for external users with SPO management shell
> new sample for SPO management shell

- docfx/report-metadata.ps1
> Small bug fix with count

- docfx/contributing/preparing-a-submission.md
Small description for script quality guidance
> Added guidance for script quality

- docfx/templates/material/styles/filtersamples.js
- scripts/_template-script-submission/assets/template.sample.json
Added a simple search feature to preserve the query in the query string allowing it to be copied and returned back.
> Add Search and Update Template

- scripts/teams-list-guestusers/README.md
- scripts/teams-list-guestusers/assets/sample.json
Hi
Just thought I'd translate the existing Teams report guest users script into PnP PowerShell and add this as an example.
Thanks
Leon
> Added PnP PowerShell example to Teams Guest users report

- scripts/spo-set-home-site/assets/sample.json
| Q               | A
| --------------- | ---
| New sample?      | no
Changed author picture URL for "Set Home site for SharePoint tenant" sample.
> Changed author picture URL

- scripts/spo-empty-tenant-recyclebin/README.md
- scripts/spo-empty-tenant-recyclebin/assets/sample.json
Hi 
I've just added a new translation of the existing empty tenant recycle bin using PnP PowerShell - just been need to do this at work so thought I'd add this quickly.
Thanks
Leon
> Added PnP PowerShell translation of empty tenant recycle bin

- scripts/spo-get-all-apps-from-appcatalog/README.md
- scripts/spo-get-all-apps-from-appcatalog/assets/sample.json
Add CLI for Microsoft 365 equivalent 👨‍💻 -
https://pnp.github.io/script-samples/spo-get-all-apps-from-appcatalog/README.html?tabs=pnpps
#214
result of the script
comparing to PnP PowerShell version
> Add CLI for Microsoft 365 to Get All Apps From The App Catalog And Export It To CSV

- scripts/spo-remove-large-library/README.md
- scripts/spo-remove-large-library/assets/sample.json
Add CLI for Microsoft 365 equivalent 👨‍💻 -
https://pnp.github.io/script-samples/spo-remove-large-library/README.html?tabs=pnpps
#215
result of the script
> Add CLI for Microsoft 365 to Delete a library exceeding the list threshold limit. Remove the files and folders before deleting the library

- docfx/assets/help/cli.help.json
- docfx/assets/help/powershell.help.json
> Refreshed help links

- scripts/spo-remove-orphaned-redirect-sites/README.md
- scripts/spo-remove-orphaned-redirect-sites/assets/sample.json
Hi
I've added just added a translation to PnP.PowerShell for the remove orphaned redirect sites example as I needed to do this in a tenant this morning.
Thanks
Leon
> Added PnP.PowerShell example for removed orphaned redirect sites example

- docfx/templates/material/styles/extra.css
- docfx/templates/material/styles/main.css
- Fixed issue where overlapping text in #227
> Fix for issue #227

- scripts/modernize-classic-pages-from-publishing-sites/README.md
- scripts/modernize-classic-pages-from-publishing-sites/assets/sample.json
Updated and tested script for transforming on-premises pages
> Updates for latest pnp powershell

- scripts/spo-list-site-externalusers/README.md
- scripts/spo-list-site-externalusers/assets/sample.json
Created script to get external users from all site collection and export it to CSV using PnP PowerShell.
> SPO-List-Site-External-Users: Created script using PnP PowerShell

- scripts/spo-add-app-catalog/README.md
- scripts/spo-add-app-catalog/assets/sample.json
Implemented Add App catalog to site collection script using SPO management shell.
> spo-add-app-catalog : Created sample using SPO management shell

- scripts/spo-hide-list-from-site-contents/README.md
- scripts/spo-hide-list-from-site-contents/assets/sample.json
Hi
Just updated Hide SharePoint list from Site Contents example to add a PnP PowerShell example.
Many thanks
> Updated Hide SharePoint list from Site Contents to add PnP PS

- scripts/spo-remove-site-designs/README.md
- scripts/spo-remove-site-designs/assets/sample.json
Needed to clear some Site Designs from my tenant so updated the CLI/SPO Example to reflect PnP PowerShell so I could run it using PnP PowerShell.
Hope this is ok
Leon
> Updated SharePoint remove site designs Script to add PnP PS

- scripts/spo-update-user-profile-properties/assets/sample.json
> spo-update-user-profile-properties: updated script title

- scripts/bulk-undelete-from-recyclebin/README.md
- scripts/bulk-undelete-from-recyclebin/assets/sample.json
Add CLI for Microsoft 365 equivalent 👨‍💻 -
https://pnp.github.io/script-samples/bulk-undelete-from-recyclebin/README.html?tabs=pnpps
#256
result of running the script that restores 4 items
> Add CLI for Microsoft 365 to Undelete items from SharePoint Recycle bin

- scripts/whiteboard-report-usage/README.md
- scripts/whiteboard-report-usage/assets/sample.json
Upgraded the script sample for below changes:
1. Used Microsoft.Graph module instead of MSOnline, being deprecated by end of year 2022.
2. Added error handling and retry scenario
3. Added logging support
> Upgraded whiteboard-report-usage

- scripts/spo-export-hub-sites-details-to-csv/README.md
- scripts/spo-export-hub-sites-details-to-csv/assets/sample.json
Upgraded `Get Hub Sites Information And Export It To CSV` sample to include `CLI for Microsoft 365` usage.
> Upgrade `Get Hub Sites Information And Export It To CSV` with CLI for Microsoft 365

- scripts/spo-export-hub-sites-details-to-csv/README.md
- scripts/spo-export-hub-sites-details-to-csv/assets/sample.json
Implemented export hub sites details script sample using `SPO management shell`.
> Implemented export hub sites details script using SPO.

- scripts/spo-update-user-profile-properties/README.md
- scripts/spo-update-user-profile-properties/assets/sample.json
This sample focuses primarily on how a user can update profile properties for a SharePoint user. 
For this, I have added an example of how this can be applied with the `CLI for Microsoft 365`.
> Upgrade `Update User Profile Properties` with CLI for Microsoft 365 sample

- scripts/user-language-for-site/README.md
- scripts/user-language-for-site/assets/sample.json
The aim fo this PR is to add cli version for script 👉https://pnp.github.io/script-samples/user-language-for-site/README.html?tabs=pnpps
#267
> CLI version for script Testing user preferred language of SharePoint site

- scripts/spo-search-export-to-csv/README.md
- scripts/spo-search-export-to-csv/assets/sample.json
Added CLI for M365 version for script "Run A Search Query And Export To CSV"
Closes #278
> CLI for M365 version for script "Run A Search Query And Export To CSV"

- scripts/spo-get-and-export-list-fields/README.md
- scripts/spo-get-and-export-list-fields/assets/sample.json
Added CLI for M365 version for script [Get SharePoint List Fields With Required properties And Export It To CSV](https://pnp.github.io/script-samples/spo-get-and-export-list-fields/README.html?tabs=pnpps)
Closes #276
> CLI for M365 version "Get SharePoint List Fields"

- scripts/planner-migration-spo-list/README.md
Add the PnP PowerShell to the planner migration to spo list
> PnP PowerShell for exporting planner to SharePoint list

- scripts/spo-get-list-library-permission-export-to-csv/README.md
- scripts/spo-get-list-library-permission-export-to-csv/assets/sample.json
Added [CLI for M365](https://pnp.github.io/cli-microsoft365/) version of script [Get SharePoint List Or Library Permissions And Export It To CSV](https://pnp.github.io/script-samples/spo-get-list-library-permission-export-to-csv/README.html?tabs=pnpps).
Closes #277
> CLI for M365 version for script "Get SharePoint List Or Library Permissions And Export It To CSV"

- scripts/spo-hub-sites-association/README.md
- scripts/spo-hub-sites-association/assets/sample.json
Upgraded `Hub Site Association` sample to include `CLI for Microsoft 365` usage.
> M365 CLI - Hub Site Association 

- scripts/fetch-user-profile-properties/README.md
- scripts/fetch-user-profile-properties/assets/sample.json
Added CLI for M365 version for script on issue #279
> Added CLI for M365 version for script "Fetch User Profile Properties From Site Collection And Export To CSV"

- scripts/spo-list-items-with-caml-query/README.md
- scripts/spo-list-items-with-caml-query/assets/sample.json
Fixed a typo in the code example. `<Geq> [...] </Eq>` is incorrect, the start and end tag should be the same. In the context of this example the correct tag is `<Eq>`.
> Update code example

- scripts/create-dummy-docs-versions-in-library/README.md
- scripts/create-dummy-docs-versions-in-library/assets/sample.json
Closes: #280 
In case of questions, feel free to ask!
> Added CLI for M365 version for script "Create bulk dummy documents, including minor/major versions, in SharePoint Document library"

- scripts/spo-export-sharepoint-list-items-to-csv/README.md
- scripts/spo-export-sharepoint-list-items-to-csv/assets/sample.json
Added CLI for M365 version for script "Export SharePoint List Data to CSV with attachments"
Closes #275
> Added CLI for M365 version for script "Export SharePoint List Data to CSV with attachments"

- scripts/teams-bulk-create-teams/README.md
- scripts/teams-bulk-create-teams/assets/sample.json
Added CLI for M365 version for script [Bulk Create Teams with JSON File](https://pnp.github.io/script-samples/teams-bulk-create-teams/README.html?tabs=pnpps).
Closes #307
> Added CLI for M365 version for script "Bulk Create Teams with JSON File"

- scripts/spo-set-home-site/README.md
- scripts/spo-set-home-site/assets/sample.json
CLI for M365 version for script [Set Home site for SharePoint tenant](https://pnp.github.io/script-samples/spo-set-home-site/README.html?tabs=pnpps).
Closes #306
> CLI for M365 version for script "Set Home site for SharePoint tenant"

- scripts/spo-remove-custom-themes/README.md
- scripts/spo-remove-custom-themes/assets/sample.json
Hello
Just added PnP PowerShell sample to SPO-Remove-Custom-Themes as noticed it was missing.
Thanks
Leon
> Added PnP PowerShell sample to SPO-Remove-Custom-Themes

- scripts/spo-add-multiple-folders-in-libraries-using-csv-file/README.md
- scripts/spo-add-multiple-folders-in-libraries-using-csv-file/assets/sample.json
Pull request for the issue https://github.com/pnp/script-samples/issues/207
> Added PnP PowerShell script for Adding multiple folders.

- scripts/spo-modern-page-publishing-report/README.md
- scripts/spo-modern-page-publishing-report/assets/sample.json
Added CLI for M365 version of script [SharePoint Modern Page Publishing Report](https://pnp.github.io/script-samples/spo-modern-page-publishing-report/README.html?tabs=pnpps).
Closes #305
> Added CLI for M365 version of script "SharePoint Modern Page Publishing Report"

- scripts/spo-list-formatting/assets/sample.json
> Update sample with cmdlet tags

- scripts/planner-migration-spo-list/assets/sample.json
Updated the needed CLI for M365 version for the sample `planner-migration-spo-list`. 
Pardon me for the inconvenience @pkbullock, but I forgot to include this in the PR #323
> Update CLI version for the sample `planner-migration-spo-list`

- scripts/spo-list-site-externalusers/README.md
- scripts/spo-list-site-externalusers/assets/sample.json
Fixes issue with wrong JMESPath in CLI sample about External Users.
> Fixes issue with wrong JMESPath in CLI sample about External Users

- scripts/planner-copy-planner-plan/README.md
- scripts/planner-copy-planner-plan/assets/sample.json
> PnP PowerShell version to copy planner plan. Closes #317

- scripts/spo-ensure-siteassets-library/README.md
- scripts/spo-ensure-siteassets-library/assets/sample.json
Updated sample script to newer version of CLI.
The script can now be run with version 5.6
> Updated sample script to newer version of CLI

- scripts/aad-apps-expired-keys/assets/sample.json
- scripts/aad-get-app-permission/assets/sample.json
- scripts/bulk-restore-from-recyclebin/assets/sample.json
- scripts/flow-export-all-flows-in-environment/assets/sample.json
- scripts/flow-export-flow-logicapp/assets/sample.json
- scripts/get-all-site-collections-subwebs/assets/sample.json
- scripts/graph-common-operations/assets/sample.json
- scripts/modernize-blog-pages/assets/sample.json
- scripts/modernize-classic-pages-from-publishing-sites/assets/sample.json
- scripts/planner-migration-spo-list/assets/sample.json
- scripts/spo-copy-webparts-to-another-page/assets/sample.json
- scripts/spo-export-data-to-sharepoint-lists/assets/sample.json
- scripts/spo-export-site-all-content/assets/sample.json
- scripts/spo-export-sitecollection-permission-with-subwebs/assets/sample.json
- scripts/spo-get-list-library-permission-export-to-csv/assets/sample.json
- scripts/spo-hub-sites-association/assets/sample.json
- scripts/spo-list-items-large-lists/assets/sample.json
- scripts/spo-recover-meeting-recordings/assets/sample.json
- scripts/whiteboard-report-usage/assets/sample.json
- Tweaks to multiple samples to find by cmdlet
> Cmdlet tagging metadata tweaks

- scripts/spo-export-termstore-terms-to-csv/README.md
- scripts/spo-export-termstore-terms-to-csv/assets/sample.json
CLI for M365 version for script "Export Term Store terms to CSV" closes #359
> CLI for M365 version for script "Export Term Store terms to CSV" closed #359

- scripts/export-onedrive-sites-details-to-csv/README.md
- scripts/export-onedrive-sites-details-to-csv/assets/sample.json
New sample to Get OneDrive sites and export it to CSV using SPO management shell.
> SPO Script Sample: Get OneDrive sites and export it to CSV.

- scripts/spo-add-bulk-users-to-groups/README.md
- scripts/spo-add-bulk-users-to-groups/assets/DummyInput.csv
- scripts/spo-add-bulk-users-to-groups/assets/sample.json
Created sample to add bulk users from CSV to SharePoint group using SPO Management shell.
> SPO management shell : Add bulk user to groups

- docfx/templates/material/partials/navbar.tmpl.partial
- docfx/templates/material/styles/main.js
- docfx/templates/material/styles/site.css
- Added stats and indicator for GitHub
- Tested on Edge and iOS devices
> Working Github Facts

- scripts/spo-activate-site-feature/README.md
- scripts/spo-activate-site-feature/assets/sample.json
I've added the feature from [this site](https://www.sharepointdiary.com/2014/08/get-feature-id-in-sharepoint-using-ie-developer-tools-firebug.html) as part of the script so it can simply be run without modifying and it'll prompt the user to choose what they wish to do.
> [spo-activate-site-feature] - Made more interactive

- scripts/graph-openai-get-page-summary/README.md
- scripts/graph-openai-get-page-summary/assets/sample.json
Updated the script to use the latest "gpt-3.5-turbo" language model - https://platform.openai.com/docs/guides/chat
> feat: updated the script to use the latest "gpt-3.5-turbo" language model

- docfx/docfx.json
- docfx/templates/material/partials/head.tmpl.partial
- Added sitemap.xml - this should have been added yonks ago, my bad
- Added webmaster token for seo management with bing.
> Added seo tweaks

- scripts/spo-export-upa-accounts/README.md
- scripts/spo-export-upa-accounts/assets/sample.json
This is for the #472 .
New sample to get user properties to csv using M365 CLI
> added sample, exort user properties using M365 CLI

- scripts/spo-add-update-image-column/README.md
- scripts/spo-add-update-image-column/assets/sample.json
Hi there! I had used your blog post to set an image column but I noticed my images weren't showing up in PowerApps (desktop browser and mobile app) or Microsoft Lists (in iOS app). You can quickly recreate this issue by using your original script and loading the list in one of those apps (Lists iOS app is easiest so you don't have to create a PowerApp tied to your list). I dug in via REST APIs to look at the value of a column that was set via the UI and noticed an 'id' value in the Image JSON, and verified that it was in fact the UniqueId of the related file. This is why I've made the small modification above to get that ID and place it in the calls. Once you do that, your images will appear correctly in PowerApps and Microsoft Lists. If you don't do that, everything will look fine in …
> Add File ID (UniqueID)

- scripts/reset-files-permission-unique-to-inherited/README.md
- scripts/reset-files-permission-unique-to-inherited/assets/sample.json
Resolves issue with the library having a large number of items or folders, tested with 5000+ folders with subfolders with unique permissions.
#373
> updated code #373

- scripts/reset-files-permission-unique-to-inherited/README.md
- scripts/reset-files-permission-unique-to-inherited/assets/sample.json
Checked CLI sample, minor changes when getting list. 
A large number of items did not impact script functionality.
> updated cli sample #373

- scripts/aad-add-app-permissions-and-connect-to-sharepoint/README.md
- scripts/aad-replace-owner-with-a-different-one/README.md
- scripts/flow-runs-status-list-dashboard/FlowDashboard.ps1
- scripts/graph-download-office-documents-as-pdf/README.md
- scripts/planner-copy-planner-plan/README.md
- scripts/report-private-teams-excel/README.md
- scripts/spo-bulk-publish-syntex-model/README.md
- scripts/spo-copy-directory-structure-to-sharepoint-list/README.md
- scripts/spo-deploy-install-update-spfx-hubsite-associatedsites/README.md
- scripts/spo-deploy-install-update-spfx-hubsite-associatedsites/assets/sample.json
- scripts/spo-enable-site-collection-app-catalog/README.md
- scripts/spo-get-message-centre-announcements-and-post-to-teams-channel/README.md
- scripts/spo-get-message-centre-announcements-and-post-to-teams-channel/assets/sample.json
- scripts/spo-set-sharepoint-regional-settings/README.md
- scripts/teams-list-teams-owners-and-members/README.md
| Q               | A
| --------------- | ---
| New sample?      | no
Small tweaks to scripts and README files (documentation) updates.
> Small tweaks and README file updates

- scripts/spo-disable-list-comments-tenant/README.md
- scripts/spo-disable-list-comments-tenant/assets/sample.json
Updated script sample with SPO Management Shell script to disable commenting feature in SharePoint online lists at tenant level.
> Sample update - Disable SharePoint List Commenting at tenant level

- scripts/spo-disable-list-comments/README.md
- scripts/spo-disable-list-comments/assets/sample.json
- Updated PnP PowerShell script to disable commenting feature in SharePoint online lists at list level
- Added CLI for Microsoft 365 script to disable commenting feature in SharePoint online lists at list level
> Sample update - Disable SharePoint List Commenting at list level

- scripts/spo-remove-site-scripts/README.md
- scripts/spo-remove-site-scripts/assets/sample.json
- Added PnP PowerShell script to delete custom SharePoint site scripts
- Added CLI for Microsoft 365 script to delete custom SharePoint site scripts
> Sample update - Delete custom SharePoint site scripts

- scripts/spo-remove-site-designs/README.md
- scripts/spo-remove-site-designs/assets/sample.json
- Added CLI for Microsoft 365 script to delete custom SharePoint site designs
> Sample update - Delete custom SharePoint site designs

- scripts/spo-empty-recycle-bin/README.md
- scripts/spo-empty-recycle-bin/assets/sample.json
- Added CLI for Microsoft 365 script to empty SharePoint Online Site Recycle Bin
> Sample Update - Empty SharePoint Online Site Recycle Bin

- scripts/spo-add-page-template/README.md
- scripts/spo-add-page-template/assets/sample.json
- Added CLI for Microsoft 365 script to add page template to SharePoint site.
> Sample Update - Add Page template to Site

- scripts/spo-update-page-banner-image/README.md
- scripts/spo-update-page-banner-image/assets/sample.json
- Added CLI for Microsoft 365 script to update SharePoint Page Banner Image.
> Sample Update - Update SharePoint Page Banner Image

- scripts/spo-remove-page-title-area/README.md
- scripts/spo-remove-page-title-area/assets/sample.json
- Added CLI for Microsoft 365 script to remove Title/Header area from SharePoint online site page.
> Sample Update - Remove Title Area from SharePoint Page

- scripts/spo-set-home-site/README.md
- scripts/spo-set-home-site/assets/sample.json
- Added SPO Management Shell script to set up home site for SharePoint online tenant.
> Sample Update - Set Home site for SharePoint tenant

- scripts/spo-activate-site-feature/README.md
- scripts/spo-activate-site-feature/assets/sample.json
- Added CLI for Microsoft 365 script to activate a site/web feature in SharePoint online site
> Sample Update - Activate a site feature in SharePoint online

- scripts/spo-associate-multiple-sites-to-hub/README.md
- scripts/spo-associate-multiple-sites-to-hub/assets/sample.json
- Added SPO Management Shell script to associate multiple SharePoint online site collections to Hub site
- Added CLI for Microsoft 365 script to associate multiple SharePoint online site collections to Hub site
> Sample Update - Associate Multiple Site Collections to Hub Site

- scripts/spo-open-doc-in-client/README.md
- scripts/spo-open-doc-in-client/assets/sample.json
- Added CLI for Microsoft 365 script to open office documents in the desktop client application if such application is installed.
> Sample Update - Open Office documents in the Client

- scripts/spo-modern-page-url-report/README.md
- scripts/spo-modern-page-url-report/assets/sample.json
The output has changed from the cmdlet I believe requiring change in script
> Updated sample 

- scripts/spo-hide-list-from-site-contents/README.md
- scripts/spo-hide-list-from-site-contents/assets/sample.json
- Updated PnP PowerShell script to hide SharePoint online list from Site Contents
- Added CLI for Microsoft 365 script to hide SharePoint online list from Site Contents
> Sample Update - Hide SharePoint list from Site Contents

- scripts/spo-empty-tenant-recyclebin/README.md
- scripts/spo-empty-tenant-recyclebin/assets/sample.json
- Added SPO Management Shell script to empty the tenant recycle bin
- Added CLI for Microsoft 365 script to empty the tenant recycle bin
> Sample Update - Empty the tenant recycle bin

- scripts/spo-create-sharepoint-groups-bulk-csv/README.md
- scripts/spo-create-sharepoint-groups-bulk-csv/assets/sample.json
- Added SPO Management Shell script to create SharePoint groups in bulk using CSV file
- Added CLI for Microsoft 365 script to create SharePoint groups in bulk using CSV file
> Sample Update - Create SharePoint Groups in Bulk using CSV file

- scripts/spo-remove-custom-themes/README.md
- scripts/spo-remove-custom-themes/assets/sample.json
- Added SPO Management Shell script to delete custom color themes from SharePoint online tenant
- Added CLI for Microsoft 365 script to delete custom color themes from SharePoint online tenant
> Sample Update - Delete custom color themes from SharePoint

- scripts/spo-add-update-image-column/README.md
- scripts/spo-add-update-image-column/assets/sample.json
- Added CLI for Microsoft 365 script to Add/Update image in SharePoint image column in a SharePoint List or Library
> Sample Update - Add/Update Image in SharePoint Image column

- scripts/spo-enable-disable-app-bar/README.md
- scripts/spo-enable-disable-app-bar/assets/sample.json
- Updated SPO Management Shell script to enable or disable App Bar in SharePoint Online
- Updated PnP PowerShell script to enable or disable App Bar in SharePoint Online
> Sample Update - Enable and Disable App Bar in SharePoint Online

- scripts/remove-delete-option-library/README.md
- scripts/remove-delete-option-library/assets/sample.json
- Updated PnP PowerShell script to remove delete option on a SharePoint document library or list with latest cmdlet updates
- Updated CLI for Microsoft 365 script to remove delete option on a SharePoint document library or list with latest cmdlet updates
> Sample Update - Remove delete option on a document library

- scripts/spo-file-version-trimmer/README.md
- scripts/spo-file-version-trimmer/assets/sample.json
Adds CLI for M365 version of [File Version Trimmer](https://pnp.github.io/script-samples/spo-file-version-trimmer/README.html?tabs=pnpps). Closes #537
> Adds CLI for M365 version of File Version Trimmer. Closes #537

- scripts/spo-add-formextension-to-list/README.md
- scripts/spo-add-formextension-to-list/assets/sample.json
- Updated PnP PowerShell script to associate SPFx form customizer extension with SharePoint list or libraries forms
- Added CLI for Microsoft 365 script to associate SPFx form customizer extension with SharePoint list or libraries forms
> Sample Update - Associate Form Customizer Extension with List or Libraries Form

- scripts/spo-deploy-install-update-spfx-hubsite-associatedsites/README.md
- scripts/spo-deploy-install-update-spfx-hubsite-associatedsites/assets/sample.json
Minor improvement to the script to increase performance
> Minor improvement to the script to increase performance

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
Not sure why this stopped working however, switching to later version helped with this.
> Fix for dev containers loading

- scripts/spo-copy-list/README.md
- scripts/spo-copy-list/assets/sample.json
added sample:
Copy list from one to other SharePoint site using PNP PowerShell. Issue #560
> updated sample for #560 issue

- scripts/spo-generate-sp-storage-savings-report/README.md
- scripts/spo-generate-sp-storage-savings-report/assets/sample.json
Updated sample from using username + password to using either -InterActive or Certificate
> Updated PnP Conn to use interactive or certificate

- scripts/spo-create-colored-folder/README.md
- scripts/spo-create-colored-folder/assets/sample.json
- Added CLI for Microsoft 365 script sample that creates a Colored Folder in a SharePoint document library.
> Sample Update - Create Colored Folder

- docfx/index.md
- scripts/azure-open-ai-byod-powershell/assets/sample.json
- scripts/graph-create-test-users-with-chat-gpt/assets/sample.json
- scripts/graph-openai-get-page-summary/assets/sample.json
- scripts/openai-function-calling-tfl-status/assets/sample.json
- Filter for AI
- Added relevant samples that use AI
> Added category filter for AI

- scripts/spo-bulk-creation-sharepoint-sites-csv/README.md
Fixed the indentation of a markdown table, currently it is looking a bit misaligned as shown in the screenshot below.
> Update README.md, fixed indentation

- New-Sample.ps1
Ref #601 - Added support for PS5
> Fix for PS5

- scripts/spo-bulk-creation-sharepoint-sites-csv/README.md
- scripts/spo-bulk-creation-sharepoint-sites-csv/assets/sample.json
- Added CLI for Microsoft 365 script sample that helps you in creation of SharePoint Online Communication and Team sites in bulk. It takes an input from CSV.
> Sample Update - Creation of SharePoint Online sites from CSV

- scripts/spo-add-fields-to-contenttypes/README.md
- scripts/spo-add-fields-to-contenttypes/assets/sample.json
- Added CLI for Microsoft 365 script sample that will create a Site Columns by checking whether it exists or not. Adds the site columns to the existing Content Types.
> Sample Update - Create Site Columns and add to Content Types

- scripts/powerapps-get-app-users-list-csv/README.md
- scripts/powerapps-get-app-users-list-csv/assets/sample.json
Updated script to include more details about app
> Update to script sample issue #631

- docfx/assets/help/cli.help.json
- docfx/assets/help/powershell.help.json
- docfx/assets/help/spoms.help.json
- docfx/report-cmdusage.ps1
- Help Updates
- Reporting counts to help show where focus could be applied
> Updates and reporting help

- scripts/spo-request-pnp-reindex-user-profile/README.md
- scripts/spo-request-pnp-reindex-user-profile/assets/sample.json
Fixing issue 
spo-request-pnp-reindex-user-profile - json error #476
> spo-request-pnp-reindex-user-profile - json error #476

- scripts/spo-add-dummy-folders-and-files/README.md
- scripts/spo-add-dummy-folders-and-files/assets/sample.json
- Added CLI for Microsoft 365 script sample that will allow you to add dummy folders and files into a SharePoint document library for bulk testing.
> Sample Update - Add dummy folders and files to a SharePoint library

- scripts/spo-add-multiple-folders-in-libraries-using-csv-file/README.md
- scripts/spo-add-multiple-folders-in-libraries-using-csv-file/assets/sample.json
- Added CLI for Microsoft 365 script samples that will allow you to create the folders into the SharePoint libraries provided in the CSV file.
> Sample Update - Add multiple folders in libraries using a CSV file

- scripts/m365-get-unifiedlog-spo-dlp-exchange-entra/README.md
- scripts/m365-get-unifiedlog-spo-dlp-exchange-entra/assets/sample.json
Update to the cli for M365 version as start date and end date more than 24 hours apart for the cli for m365 equivalent.
> Update to the cli for M365 version

- scripts/spo-reindex-sites/README.md
- scripts/spo-reindex-sites/assets/sample.json
Added text and a pause in the script to ensure people have read the text before proceeding.
@pkbullock
> Added text to highlight when this script is ok to run.

- scripts/spo-dev-tenant-report-export/README.md
- scripts/spo-dev-tenant-report-export/assets/sample.json
- Updated cmds
- Improved Azure AD Apps
> Sample update

- scripts/spo-reindex-sites/README.md
- scripts/spo-reindex-sites/assets/sample.json
- Added CLI for Microsoft 365 script samples that streamlines the process of re-indexing sites to ensure that search results remain accurate and relevant.
Closes #667.
> Sample Update - Reindex SharePoint sites. Closes #667

- scripts/spo-check-unaccessable-homepages/README.md
- scripts/spo-check-unaccessable-homepages/assets/sample.json
- Added CLI for Microsoft 365 script sample that looks for the site collections where site home page has custom permissions and outputs to a CSV file.
> Sample Update - Scan for potential inaccessible site collection homepages

- scripts/spo-get-customfields-lists/README.md
- scripts/spo-get-customfields-lists/assets/sample.json
- Added CLI for Microsoft 365 script sample that lists all custom columns/fields created in SharePoint lists and libraries excluding out of the box lists and fields.
> Sample Update - List custom fields from SharePoint Lists or libraries

- docfx/templates/material/styles/main.js
Ref #688 
- Acted on recommended from security analysis
> Multiple recommended security fixes

- scripts/power-automate-replace-owner/README.md
- scripts/power-automate-replace-owner/assets/sample.json
PnP PowerShell version of the script to replace owner in power automate flows
> PnP PowerShell version of the script to replace owner in power automate flows

- scripts/aad-ensure-ownersaremembers-m365groups/README.md
- scripts/aad-ensure-ownersaremembers-m365groups/assets/sample.json
- scripts/spo-export-report-files-incidents/assets/sample.json
Hi,
As mentioned in the PR, I have added the script in the CLI for the M365  version to the `aad-ensure-owneraremembers-m365group` script.
I am also adding @reshmee011 because I have made some modifications to the initial PnP script, so let's confirm with her if the changes are ok.
> Adds CLI for M365 version of aad-ensure-owneraremembers-m365group script

- docfx/index.md
- scripts/_template-script-submission/assets/template.sample.json
- scripts/spo-delete-sharinglink-folder-file-item/assets/sample.json
- scripts/spo-enable-disable-search-crawling/assets/sample.json
- scripts/spo-get-permission-audit/assets/sample.json
- scripts/spo-get-sharinglinks/assets/sample.json
- scripts/teams-list-all-app-descriptions/assets/sample.json
- Added Filter
- Updated sample template to allow quick filters
- Updated known samples related to Copilot
> Add Copilot Category and Filters

- scripts/spo-apply-pnptemplate-with-files-and-listitems/README.md
Hi, I have just corrected a small typo in one of the script’s description.
> Fix small typo in spo-apply-pnptemplate-with-files-and-listitems

- scripts/spo-remove-teamify-link/README.md
- scripts/spo-remove-teamify-link/assets/sample.json
This PR is to propose an alternative to hide the prompt to teamify a site without enabling custom scripting on the site.
> Alternative cmdlet hide team prompt

- scripts/spo-remove-teamify-link/README.md
- scripts/spo-remove-teamify-link/assets/sample.json
Added CLI version for:
"Remove the Teamify link on Group sites" 
https://pnp.github.io/script-samples/spo-remove-teamify-link/README.html?tabs=pnpps
> Added addition to "Remove the Teamify link on Group sites" 

- docfx/toc.yml
> Add adoption gallery link

- docfx/index.md
- scripts/_template-script-submission/assets/template.sample.json
- scripts/spo-delete-sharinglink-folder-file-item/assets/sample.json
- scripts/spo-enable-disable-search-crawling/assets/sample.json
- scripts/spo-get-permission-audit/assets/sample.json
- scripts/spo-get-sharinglinks/assets/sample.json
- scripts/teams-list-all-app-descriptions/assets/sample.json
- Adjusted Filters
- Updated categories for the product name
References #715
> Adjusted samples for Microsoft 365 Copilot

- docfx/index.md
- Replace the solution gallery and add the extensions
> Banner tweaks

- README.md
Ops, that disappeared - restoring.
> Restore README.md

- docfx/includes/MORE-CLIM365.md
- docfx/includes/MORE-PNPPS.md
- docfx/templates/material/styles/main.css
Based on upcoming change to the way users login into PnP PowerShell or CLI for Microsoft 365
Warnings placed on includes where the script is used in both cases.
> Warning of upcoming change

- docfx/index.md
- docfx/templates/material/styles/main.css
Highlight text on the home page to the upcoming change.
> Emphasis on change

- scripts/spo-file-version-trimmer/README.md
- scripts/spo-file-version-trimmer/assets/sample.json
Added another example how to trim version using enhanced version control.
> Add Enhanced Version Control sample to trim version

- scripts/spo-get-site-sharing-settings/README.md
- scripts/spo-get-site-sharing-settings/assets/sample.json
remove hard coded url and added a couple of settings.
> Update README.md with minor tweaks and additional settings

- .tours/contributing.tour
- docfx/contributing/preparing-a-submission.md
- Added a code tour walkthrough to describe areas of a sample submission to complete this quickly
- Update contributor guidance to find the walkthrough.
> Add CodeTour workthrough

- scripts/spo-generate-sp-storage-savings-report/README.md
- scripts/spo-generate-sp-storage-savings-report/assets/sample.json
> updated name of output files to include the amount of space saved

- scripts/spo-get-permission-audit/README.md
- scripts/spo-get-permission-audit/assets/sample.json
Add sensitivity label and optimise the script to be faster.
> Add sensitivity label and optimise the script

- scripts/spo-download-files-from-doclib/README.md
- scripts/spo-download-files-from-doclib/assets/sample.json
cli-m365-ps added to spo-download-files
> spo-download-files added  cli-m365-ps

- scripts/aad-get-tenantid/README.md
- scripts/aad-get-tenantid/assets/sample.json
Propose PnP PowerShell alternative to get tenant Id
Updated README.md with the alternative
> Propose PnP PowerShell alternative to get tenant Id 

- scripts/spo-get-site-sharing-settings/README.md
- scripts/spo-get-site-sharing-settings/assets/sample.json
Update script with sensitivity label, type of m365 group and allowtoaddguest settings
> Update to add sensitivity label, type of m365 group and allowtoaddguest

- docfx/Get-HelpJson.ps1
- docfx/assets/help/cli.help.json
- docfx/assets/help/powershell.help.json
- docfx/assets/help/spoms.help.json
- Updated support script
- Update Help Json files based on project changes
> Updated Help

- scripts/aad-grant-serviceprincipal-api-permissions/README.md
- scripts/fetch-user-profile-properties/README.md
- scripts/powerapps-get-all-bootstrap-icons/README.md
- scripts/spo-add-document-library-webpart-to-page/README.md
- scripts/spo-bulk-delete-recyclebin-in-batch-avoid-lvt/assets/sample.json
- scripts/spo-delete-site-with-retention-policy/README.md
- scripts/spo-delete-unused-spfx-apipermissions/README.md
- scripts/spo-extract-and-invoke-site-template/assets/sample.json
- scripts/teams-bulk-create-teams/README.md
- Missing GitHub Handles
- Added telemetry paths correctly
> Small quality updates

- docfx/report-matrix.ps1
Bug in report
needed to test locally.
Fixed now hopefully.
> Fix report

- docfx/compact-view.md
- docfx/index.md
- docfx/templates/material/styles/extra.css
- docfx/templates/material/styles/main.css
Fixed text overlapping
Adjusted the intro text
Closes #775
> Fixes to breakpoint issues

- scripts/aad-get-tenantid/README.md
- scripts/aad-get-tenantid/assets/sample.json
- Script Metadata tags update and typo fixes in description.
> Sample Update - Get Tenant ID

- scripts/spo-get-everyone-everyoneexceptexternalusers/README.md
> Update README.md to remove unnecessary line

- scripts/spo-get-everyone-everyoneexceptexternalusers/README.md
- scripts/spo-get-everyone-everyoneexceptexternalusers/assets/sample.json
clarify instructions and fix script for spo-get-everyone-everyoneexceptexternalusers
https://pnp.github.io/script-samples/spo-get-everyone-everyoneexceptexternalusers/README.html?tabs=pnpps
> fix script and add instructions for spo-get-everyone-everyoneexceptexternalusers

- .gitignore
Added Mac files to gitignore
fix #800
> chore: add mac files to gitignore

- docfx/build.ps1
- docfx/report-age.ps1
- Age report of samples in prep for rangers
- list out oooooold samples 
- Lets see if it breaks build lol
Ref #815
> added  age report

- docfx/report-age.ps1
- Removed categories (just adds noise)
> Tweaked Output

- .github/copilot-instructions.md
- Adding a new instructions file for those with Copilot chat, to help contributors create samples
> Added instructions file

- README.md
- docfx/Get-HelpJson.ps1
- docfx/assets/help/cli.help.json
- docfx/assets/help/powershell.help.json
- docfx/assets/help/spoms.help.json
This pull request updates command documentation and help URLs for the Microsoft 365 CLI, primarily by adding new command entries and updating or removing outdated ones in `docfx/assets/help/cli.help.json`. It also includes a small update to the repository's `README.md`. The main changes are grouped below for clarity.
**New command help entries:**
* Added help URLs for new commands across multiple services, including Microsoft Entra, Exchange Online, Graph, Outlook, Power Platform, SharePoint, and SharePoint Embedded. This greatly expands the discoverability and documentation coverage for users. [[1]](diffhunk://#diff-8485b8c95fa5ea01cafaea764f42806c6bf88d1734613a6466c45c0b71e6804eR78-R85) [[2]](diffhunk://#diff-8485b8c95fa5ea01cafaea764f42806c6bf88d1734613a6466c45c0b71e6804eR286-R289) …
> Help Link and File Updates to Documentation Sites and Tracking
